<template>
  <v-container>
    <v-row class="text-center">
      <v-col>
        <div class="title mb-4">Required Details</div>
        <v-text-field
            v-for="field in formFieldsRequired"
            :key="field.key"
            :label="field.label"
            :hint="field.hint"
            :rules="field.rules ? field.rules : []"
            persistent-hint
            v-model="formData[field.key]"
            filled />

        <div class="title mb-4">Optional Details</div>
        <v-text-field
            v-for="field in formFieldsOptional"
            :key="field.key"
            :label="field.label"
            :hint="field.hint"
            :rules="field.rules ? field.rules : []"
            :type="field.type"
            persistent-hint
            v-model="formData[field.key]"
            filled />
        <v-select
            :items="redirectTargets"
            v-model="formData.target"
            filled
            label="Redirect Target"
            hint="Select where the redirect would open" />
        <v-switch
            v-model="formData.captcha"
            hint="force the captcha"
            label="Use Recaptcha" />

        <div class="title mb-4">Other Options</div>
        <p class="label">Submit Color</p>
        <div class="d-flex justify-center">
          <v-color-picker v-model="formData.color" flat mode="rgba" />
        </div>

        <div class="title mb-4">Default Values</div>
        <v-text-field
            v-for="field in formFields.filter(p => !['Name', 'Email', 'MobilePhone'].includes(p.key))"
            :key="'defaults-' + field.key"
            :label="field.label"
            :hint="field.hint"
            :rules="field.rules ? field.rules : []"
            persistent-hint
            v-model="formData['default' + field.key]"
            filled />

        <div class="title mb-4">Placeholder Values</div>
        <p>The text you see in the field before a user fills a form</p>
        <v-text-field
            v-for="field in formFields.filter(p => !['Thanks'].includes(p.key))"
            :key="'place-' + field.key"
            :label="field.label"
            :hint="field.hint"
            :rules="field.rules ? field.rules : []"
            persistent-hint
            v-model="formData['place' + field.key]"
            filled />

      </v-col>
      <v-col>
        <div class="title mb-4">Embed Code</div>
        <v-textarea
          filled
          readonly
          auto-grow
          :value="textAreaValue" />

        <div class="title mb-4">Preview Form</div>
        <div class="iframe-container" v-html="textAreaValue"></div>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
  const rules = {
    requiredRule: value => !!value || 'Required',
  }

  export default {
    name: 'Form',

    data: () => ({
      formData: {
        officeID: '',
        referralSource: '',
        timeout: 10,
        target: '_top',
        color: '#FF7F00',

        // Placeholders
        placeName: 'Full Name',
        placeEmail: 'Email Address',
        placeMobilePhone: 'Phone Number',
        placeComments: 'What would you like to know?',

        // Default Values
        defaultThanks: 'Your form submission has been received. We will be in touch shortly.'
      },

      formFieldsRequired: [
        {
          key: 'officeID',
          label: 'Office ID',
          hint: 'Needs to be a valid LockedOn UUID of an existing office with enabled enquiry access',
          rules: [rules.requiredRule]
        }, {
          key: 'referralSource',
          label: 'Referral Source',
          hint: 'Needs to be the same as what it is in LockedOn',
          rules: [rules.requiredRule]
        }
      ],

      formFieldsOptional: [
        {
          key: 'property',
          label: 'Property ID',
          hint: `Needs to be a valid LockedOn UUID, belonging to the given office. If not then all enquiries
will not be linked to a property`
        }, {
          key: 'referral-source-id',
          label: 'Referral Source ID',
          hint: `generated by customer`
        }, {
          key: 'redirectURL',
          label: 'Redirect URL',
          hint: `Send someone to another page or file download, after the
form was successfully submited`
        }, {
          key: 'timeout',
          label: 'Timeout (seconds)',
          type: 'number',
          hint: 'Control how long the thank you message will be visible'
        }
      ],

      formFields: [
        {
          key: 'Thanks',
          label: 'Thank You Message',
          hint: 'The thank you message after submission',
          rules: [rules.requiredRule]
        }, {
          key: 'Name',
          label: 'Name'
        }, {
          key: 'Email',
          label: 'Email'
        }, {
          key: 'MobilePhone',
          label: 'Mobile Phone'
        }, {
          key: 'Comments',
          label: 'Comments'
        }
      ],

      redirectTargets: [
        {
          text: 'New Tab',
          value: '_blank'
        }, {
          text: 'Same Tab',
          value: '_top'
        }
      ]
    }),

    methods: {
      restoreFromLocal () {
        if (localStorage.getItem('lockedon-form-state')) {
          this.formData = JSON.parse(localStorage.getItem('lockedon-form-state'))
        }
      },

      saveToLocal () {
        localStorage.setItem("lockedon-form-state", JSON.stringify(this.formData));
      }
    },

    mounted () {
      this.restoreFromLocal()
      setInterval(() => {this.saveToLocal()}, 5000)
    },

    computed: {
      textAreaValue () {
        const requiredKeys = this.formFieldsRequired.map(f => f.key)
        let isRequiredFilled = true
        requiredKeys.forEach(k => {
          if (isRequiredFilled && !this.formData[k]) {
            isRequiredFilled = false
          }
        })
        if (isRequiredFilled) {
          let form = `<iframe 
width="100%" 
height="400px" 
frameborder="0" 
overflow="hidden" 
src='https://d12maig5xvucum.cloudfront.net/enquiry/web-enquiry.html?
property=${this.formData.property} 
&referral-source=${this.formData.referralSource} 
&office=${this.formData.officeID} 
${this.theme}
${this.defaults}
${this.placeholder}
&redirect_url=${this.formData.redirectURL}
&target=${this.formData.target}
&timeout=${this.formData.timeout}
${this.formData.captcha ? '&use-recaptcha=1' : ''}
'></iframe>`
          return form.split(/\n/).join('')
        }
        return ''
      },

      theme () {
        return `&theme=
{
"%23enquiry-form > div:first-of-type":{"display":"none"},
"%23enquiry-form":{"margin-top":"30px"},
"label":{"color":"white", "font-family":"Montserrat, sans-serif",
"font-size":".7em",
"text-transform":"uppercase",
"display":"none"},
"input":{"font-family":"Montserrat, sans-serif",
"width":"99%25",
"margin":"0 1.5px 6px 0",
"text-transform":"uppercase",
"height":"45px"},
"textarea":{"width":"99%25",
"margin":"0 0 0 1.5px",
"height":"147px"},
"input[name=name]":{"place":"YourName"},
"input[type=submit]":{"background":"${this.colorSelected}",
"box-shadow":"none", "padding":"12px",
"font-family":"Montserrat-Bold, sans-serif",
"float":"none","overflow":"hidden",
"width":"100%25",
"margin":"5px 1px 0 0"},
"%23thanks":{"color":"white",
"font-family":"Montserrat,sans-serif"
}}`
      },

      defaults () {
        return `&defaults={
${this.formData.defaultThanks ? '"thanks":"' + this.formData.defaultThanks + '"' : ''}
${this.formData.defaultComments ? ',"comments":"' + this.formData.defaultComments + '"' : ''}
}`.split(/\n/).join('')
      },

      placeholder () {
        return `&place={
${this.formData.placeName ? '"name":"' + this.formData.placeName + '",' : ''}
${this.formData.placeEmail ? '"email":"' + this.formData.placeEmail + '",' : ''}
${this.formData.placeMobilePhone ? '"mobile-phone":"' + this.formData.placeMobilePhone + '",' : ''}
${this.formData.placeComments ? '"comments":"' + this.formData.placeComments + '"' : ''}
}`.split(/\n/).join('')
      },

      colorSelected() {
        let result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(this.formData.color);
        return result
          ? `rgb(${parseInt(result[1], 16)},${parseInt(result[2], 16)},${parseInt(result[3], 16)})`
          : 'rgb(240,78,35)';
      }
    },
  }
</script>
